### PR TITLE
add plugin setting file for strapi-provider-upload-azure-storage

### PR DESCRIPTION
**Pull request by hhatto**
change of #69, I forgot to commit the configuration file for `strapi-provider-upload-azure-storage`.
sorry, my mistake.

@aggre  When I merged it into the main branch, did it deploy automatically?  If not, I'd like to deploy it again 🙏

### CODE REVIEW

**Comment by aggre** [comment]
@hhatto https://github.com/dev-protocol/dev-for-apps/commit/84e907aa46934c077cc01aea104dfc1b42464f3b seems to have been deployed.

Azure Web Apps for Containers has a 5-10 minute delay before the deployment takes effect.

FYI: https://dev.azure.com/dev-protocol/dev-for-apps/_build?definitionId=5 (Can you access it?)

**Comment by hhatto** [comment]
> Azure Web Apps for Containers has a 5-10 minute delay before the deployment takes effect.

I see.

> FYI: https://dev.azure.com/dev-protocol/dev-for-apps/_build?definitionId=5 (Can you access it?)

umm, the DevOps page appears for a moment, but the error is as follows It looks like you don't have permissions.
error

**Comment by aggre** [comment]
I added you as an organization member!

**Comment by hhatto** [comment]
> I added you as an organization member!

thx!! It's now available for viewing.

**Pull request merged**
